export enum AnalyticsEventTypeEnum {
  UNVERIFIED_SIGN_UP = 'UNVERIFIED_SIGN_UP',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}
