'use client';

import {
  Users,
  CreditCard,
  Bug,
  Image,
  TrendingUp,
  TrendingDown,
  Activity,
} from 'lucide-react';

interface StatCardProps {
  title: string;
  value: string | number;
  change?: number;
  icon: React.ReactNode;
  trend?: 'up' | 'down' | 'neutral';
}

function StatCard({ title, value, change, icon, trend }: StatCardProps) {
  return (
    <div className="admin-card flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <span className="text-sm text-muted-foreground">{title}</span>
        <div className="p-2 rounded-lg bg-primary/10 text-primary">{icon}</div>
      </div>
      <div>
        <p className="text-2xl md:text-3xl font-bold">{value}</p>
        {change !== undefined && (
          <div className="flex items-center gap-1 mt-1">
            {trend === 'up' ? (
              <TrendingUp className="w-4 h-4 text-green-400" />
            ) : trend === 'down' ? (
              <TrendingDown className="w-4 h-4 text-red-400" />
            ) : null}
            <span
              className={`text-sm ${
                trend === 'up'
                  ? 'text-green-400'
                  : trend === 'down'
                  ? 'text-red-400'
                  : 'text-muted-foreground'
              }`}
            >
              {change > 0 ? '+' : ''}
              {change}% from last week
            </span>
          </div>
        )}
      </div>
    </div>
  );
}

interface RecentActivityItem {
  id: string;
  type: 'user' | 'payment' | 'bug' | 'content';
  message: string;
  time: string;
}

function getActivityIcon(type: RecentActivityItem['type']) {
  switch (type) {
    case 'user':
      return <Users className="w-4 h-4" />;
    case 'payment':
      return <CreditCard className="w-4 h-4" />;
    case 'bug':
      return <Bug className="w-4 h-4" />;
    case 'content':
      return <Image className="w-4 h-4" />;
  }
}

function getActivityColor(type: RecentActivityItem['type']) {
  switch (type) {
    case 'user':
      return 'bg-blue-500/20 text-blue-400';
    case 'payment':
      return 'bg-green-500/20 text-green-400';
    case 'bug':
      return 'bg-red-500/20 text-red-400';
    case 'content':
      return 'bg-purple-500/20 text-purple-400';
  }
}

// Mock data - replace with real API calls
const MOCK_STATS = {
  totalUsers: 2458,
  usersChange: 12.5,
  totalRevenue: '$45,892',
  revenueChange: 8.2,
  openBugs: 23,
  bugsChange: -15,
  imagesGenerated: 128420,
  imagesChange: 25.3,
};

const MOCK_ACTIVITY: RecentActivityItem[] = [
  {
    id: '1',
    type: 'user',
    message: 'New user registered: john@example.com',
    time: '2 min ago',
  },
  {
    id: '2',
    type: 'payment',
    message: 'Subscription upgraded: Pro plan ($79/mo)',
    time: '5 min ago',
  },
  {
    id: '3',
    type: 'bug',
    message: 'Bug #142 marked as resolved',
    time: '12 min ago',
  },
  {
    id: '4',
    type: 'content',
    message: '50 new images generated by user_a843',
    time: '18 min ago',
  },
  {
    id: '5',
    type: 'payment',
    message: 'Credit purchase: 500 credits ($49)',
    time: '25 min ago',
  },
];

export default function DashboardPage() {
  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h2 className="text-xl md:text-2xl font-bold">Dashboard</h2>
        <p className="text-muted-foreground mt-1">
          Overview of your platform metrics
        </p>
      </div>

      {/* Stats grid - responsive columns */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title="Total Users"
          value={MOCK_STATS.totalUsers.toLocaleString()}
          change={MOCK_STATS.usersChange}
          trend="up"
          icon={<Users className="w-5 h-5" />}
        />
        <StatCard
          title="Revenue (MTD)"
          value={MOCK_STATS.totalRevenue}
          change={MOCK_STATS.revenueChange}
          trend="up"
          icon={<CreditCard className="w-5 h-5" />}
        />
        <StatCard
          title="Open Bugs"
          value={MOCK_STATS.openBugs}
          change={MOCK_STATS.bugsChange}
          trend="down"
          icon={<Bug className="w-5 h-5" />}
        />
        <StatCard
          title="Images Generated"
          value={MOCK_STATS.imagesGenerated.toLocaleString()}
          change={MOCK_STATS.imagesChange}
          trend="up"
          icon={<Image className="w-5 h-5" />}
        />
      </div>

      {/* Content sections */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recent activity */}
        <div className="admin-card">
          <div className="flex items-center gap-2 mb-4">
            <Activity className="w-5 h-5 text-primary" />
            <h3 className="text-lg font-semibold">Recent Activity</h3>
          </div>
          <div className="space-y-3">
            {MOCK_ACTIVITY.map((item) => (
              <div
                key={item.id}
                className="flex items-start gap-3 p-3 rounded-lg bg-secondary/50"
              >
                <div
                  className={`p-2 rounded-lg ${getActivityColor(item.type)}`}
                >
                  {getActivityIcon(item.type)}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm">{item.message}</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    {item.time}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Quick actions */}
        <div className="admin-card">
          <h3 className="text-lg font-semibold mb-4">Quick Actions</h3>
          <div className="grid grid-cols-2 gap-3">
            <Link
              href={routes.users}
              className="flex flex-col items-center gap-2 p-4 rounded-lg bg-secondary/50 hover:bg-secondary transition-colors min-h-[88px]"
            >
              <Users className="w-6 h-6 text-primary" />
              <span className="text-sm font-medium text-center">
                View Users
              </span>
            </Link>
            <Link
              href={routes.billing}
              className="flex flex-col items-center gap-2 p-4 rounded-lg bg-secondary/50 hover:bg-secondary transition-colors min-h-[88px]"
            >
              <CreditCard className="w-6 h-6 text-primary" />
              <span className="text-sm font-medium text-center">Billing</span>
            </Link>
            <Link
              href={routes.bugs}
              className="flex flex-col items-center gap-2 p-4 rounded-lg bg-secondary/50 hover:bg-secondary transition-colors min-h-[88px]"
            >
              <Bug className="w-6 h-6 text-primary" />
              <span className="text-sm font-medium text-center">
                Bug Reports
              </span>
            </Link>
            <Link
              href={routes.content}
              className="flex flex-col items-center gap-2 p-4 rounded-lg bg-secondary/50 hover:bg-secondary transition-colors min-h-[88px]"
            >
              <Image className="w-6 h-6 text-primary" />
              <span className="text-sm font-medium text-center">Content</span>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
