/**
 * Character Wizard Store
 * Zustand store with localStorage persistence for the 6-step character creation wizard
 *
 * Source: MDC mdc-next-frontend/store/persist/character-presets-form.ts
 * Adapted for RYLA MVP
 */

import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import { immer } from 'zustand/middleware/immer';

/** Wizard step definition */
export interface WizardStep {
  id: number;
  title: string;
  description?: string;
}

import { GeneratedImage, ProfilePictureImage } from './types';

/** Character form data matching the wizard */
export interface CharacterFormData {
  // Step 0: Creation Method
  creationMethod:
    | 'presets'
    | 'prompt-based'
    | 'ai'
    | 'custom'
    | 'existing-person'
    | null;

  // Prompt-based Flow Fields
  promptInput?: string; // Single prompt for character description
  aiDescription?: string; // Detailed description generated or input for character
  aiGeneratedConfig?: any; // Config object generated by AI
  promptEnhance?: boolean; // Enable AI prompt enhancement (default: true)
  voiceMemoUrl?: string; // URL to uploaded voice memo (future)

  // Legacy fields (for migration)
  customAppearancePrompt?: string;
  customIdentityPrompt?: string;
  customImagePrompt?: string;

  // Step 1: Style
  gender: 'female' | 'male' | null;
  style: 'realistic' | 'anime' | null;

  // Step 2: General (Basic Appearance)
  ethnicity: string | null;
  ageRange: string | null; // Age range instead of age slider
  age: number; // Keep for backward compatibility
  skinColor: string | null;

  // Step 3: Face (Facial Features)
  eyeColor: string | null;
  faceShape: string | null;

  // Step 3.5: Hair (separate step)
  hairStyle: string | null;
  hairColor: string | null;

  // Step 4: Body
  bodyType: string | null;
  assSize: string | null;
  breastSize: string | null; // Female only
  breastType: string | null; // Different from breastSize

  // Step 6: Skin Features
  freckles: string | null;
  scars: string | null;
  beautyMarks: string | null;

  // Step 7: Body Modifications
  piercings: string | null;
  tattoos: string | null;

  // Step 9: Advanced
  voice: string | null;
  videoContentOptions: string[];

  // Step 5: Identity
  name: string;
  outfit: string | null;
  archetype: string | null;
  personalityTraits: string[];
  bio: string; // Optional - can be empty string

  // Generation settings
  nsfwEnabled: boolean;
  aspectRatio: '1:1' | '9:16' | '2:3';
  // qualityMode removed - see EP-045

  // LoRA training for character consistency
  loraTrainingEnabled: boolean;

  // Profile picture set selection (null = skip)
  selectedProfilePictureSetId:
    | 'classic-influencer'
    | 'professional-model'
    | 'natural-beauty'
    | null;

  // Existing Person Request Flow Fields
  influencerRequestConsent?: boolean;
  influencerRequestInstagram?: string;
  influencerRequestTikTok?: string;
  influencerRequestDescription?: string;
}

/** Store state interface */
export interface CharacterWizardState {
  // Navigation
  step: number;
  steps: WizardStep[];
  status: 'idle' | 'pending' | 'generating' | 'completed' | 'error';

  // Form data
  form: CharacterFormData;

  // Base image selection
  baseImages: GeneratedImage[]; // 3 generated base images
  selectedBaseImageId: string | null;
  baseImageFineTunePrompt: string; // For fine-tuning selected image

  // Base image generation tracking (for prompt-based flow)
  baseImageJobId: string | null; // Primary job ID
  baseImageAllJobIds: string[] | null; // All job IDs for parallel generation
  baseImageGenerationStartedAt: number | null; // Timestamp when generation started

  // Profile picture set
  profilePictureSet: {
    jobId: string | null;
    images: ProfilePictureImage[];
    generating: boolean;
    setId?: 'classic-influencer' | 'professional-model' | 'natural-beauty';
  };

  // Generated character ID (after creation)
  characterId: string | null;

  // Actions
  setStep: (step: number) => void;
  nextStep: () => void;
  prevStep: () => void;
  setStatus: (status: CharacterWizardState['status']) => void;
  setCharacterId: (id: string | null) => void;
  updateSteps: (
    method: 'presets' | 'prompt-based' | 'ai' | 'custom' | 'existing-person'
  ) => void;

  // Form actions
  setField: <K extends keyof CharacterFormData>(
    field: K,
    value: CharacterFormData[K]
  ) => void;
  setFormData: (data: Partial<CharacterFormData>) => void;
  resetForm: () => void;

  // Base image actions
  setBaseImages: (images: GeneratedImage[]) => void;
  selectBaseImage: (imageId: string | null) => void;
  setBaseImageFineTunePrompt: (prompt: string) => void;
  replaceBaseImage: (imageId: string, newImage: GeneratedImage) => void;
  setBaseImageJobIds: (jobId: string, allJobIds: string[]) => void;
  clearBaseImageJobIds: () => void;

  // Profile picture set actions
  setProfilePictureSetGenerating: (generating: boolean) => void;
  setProfilePictureSetJobId: (jobId: string | null) => void;
  setProfilePictureSetImages: (images: ProfilePictureImage[]) => void;
  addProfilePicture: (image: ProfilePictureImage) => void;
  removeProfilePicture: (imageId: string) => void;
  updateProfilePicture: (
    imageId: string,
    updates: Partial<ProfilePictureImage>
  ) => void;

  // Validation
  isStepValid: (step: number) => boolean;
  canProceed: () => boolean;

  // Navigation helpers
  getNextStepNumber: () => number | null;
  getPrevStepNumber: () => number | null;
  getEffectiveStepCount: () => number;
}

/** Default wizard steps - will be dynamically built based on creation method */
const PRESETS_STEPS: WizardStep[] = [
  { id: 1, title: 'Style', description: 'Choose gender and style' },
  { id: 2, title: 'Ethnicity', description: 'Select ethnicity' },
  { id: 3, title: 'Age Range', description: 'Select age range' },
  { id: 4, title: 'Skin Color', description: 'Select skin color' },
  { id: 5, title: 'Eye Color', description: 'Select eye color' },
  { id: 6, title: 'Face Shape', description: 'Select face shape' },
  { id: 7, title: 'Hair Style', description: 'Select hair style' },
  { id: 8, title: 'Hair Color', description: 'Select hair color' },
  { id: 9, title: 'Body Type', description: 'Select body type' },
  { id: 10, title: 'Ass Size', description: 'Select ass size' },
  { id: 11, title: 'Breast Size', description: 'Select breast size' },
  { id: 12, title: 'Breast Type', description: 'Select breast type' },
  { id: 13, title: 'Freckles', description: 'Select freckles' },
  { id: 14, title: 'Scars', description: 'Select scars' },
  { id: 15, title: 'Beauty Marks', description: 'Select beauty marks' },
  { id: 16, title: 'Piercings', description: 'Select piercings' },
  { id: 17, title: 'Tattoos', description: 'Select tattoos' },
  { id: 18, title: 'Outfit', description: 'Choose default outfit' },
  { id: 19, title: 'Archetype', description: 'Choose persona type' },
  { id: 20, title: 'Personality', description: 'Add name and personality' },
  { id: 21, title: 'Base Image', description: 'Select your character face' },
  { id: 22, title: 'Finalize', description: 'Review and create' },
];

const PROMPT_BASED_STEPS: WizardStep[] = [
  { id: 1, title: 'Prompt Input', description: 'Describe your character' },
  { id: 2, title: 'Identity', description: 'Name and personality' },
  { id: 3, title: 'Base Image', description: 'Select your character face' },
  { id: 4, title: 'Finalize', description: 'Review and create' },
];

const EXISTING_PERSON_STEPS: WizardStep[] = [
  {
    id: 1,
    title: 'Request Influencer',
    description: 'Submit request with consent and details',
  },
];

/**
 * Reset form fields and state for steps from a given step onwards
 * This is called when going back in the wizard to clear invalidated data
 */
function resetStepsFrom(state: CharacterWizardState, fromStep: number): void {
  const { form } = state;
  const { creationMethod } = form;

  if (creationMethod === 'prompt-based') {
    // Prompt-based flow: 1=Prompt, 2=Identity, 3=Base Image, 4=Finalize
    if (fromStep <= 1) {
      // Reset prompt input
      form.promptInput = undefined;
      // Also clear downstream steps
      form.name = '';
      form.outfit = null;
      form.archetype = null;
      form.personalityTraits = [];
      form.bio = '';
      state.baseImages = [];
      state.selectedBaseImageId = null;
      state.baseImageFineTunePrompt = '';
      state.baseImageJobId = null;
      state.baseImageAllJobIds = null;
      state.baseImageGenerationStartedAt = null;
    }
    if (fromStep <= 2) {
      // Reset identity
      form.name = '';
      form.outfit = null;
      form.archetype = null;
      form.personalityTraits = [];
      form.bio = '';
      // Also clear base images since they may depend on identity
      state.baseImages = [];
      state.selectedBaseImageId = null;
      state.baseImageFineTunePrompt = '';
      state.baseImageJobId = null;
      state.baseImageAllJobIds = null;
      state.baseImageGenerationStartedAt = null;
    }
    if (fromStep <= 3) {
      // Reset base image selection
      state.baseImages = [];
      state.selectedBaseImageId = null;
      state.baseImageFineTunePrompt = '';
      state.baseImageJobId = null;
      state.baseImageAllJobIds = null;
      state.baseImageGenerationStartedAt = null;
    }
    // Profile pictures are generated after creation on the profile page.
  } else if (creationMethod === 'presets') {
    // Presets flow
    if (fromStep <= 1) {
      // Reset style
      form.gender = null;
      form.style = null;
    }
    if (fromStep <= 2) {
      // Reset ethnicity
      form.ethnicity = null;
    }
    if (fromStep <= 3) {
      // Reset age range
      form.ageRange = null;
      form.age = 25; // Reset to default
    }
    if (fromStep <= 4) {
      // Reset skin color
      form.skinColor = null;
    }
    if (fromStep <= 5) {
      // Reset eye color
      form.eyeColor = null;
    }
    if (fromStep <= 6) {
      // Reset face shape
      form.faceShape = null;
    }
    if (fromStep <= 7) {
      // Reset hair style
      form.hairStyle = null;
    }
    if (fromStep <= 8) {
      // Reset hair color
      form.hairColor = null;
    }
    if (fromStep <= 9) {
      // Reset body type
      form.bodyType = null;
    }
    if (fromStep <= 10) {
      // Reset ass size
      form.assSize = null;
    }
    if (fromStep <= 11) {
      // Reset breast size
      form.breastSize = null;
    }
    if (fromStep <= 12) {
      // Reset breast type
      form.breastType = null;
    }
    if (fromStep <= 13) {
      // Reset freckles
      form.freckles = null;
    }
    if (fromStep <= 14) {
      // Reset scars
      form.scars = null;
    }
    if (fromStep <= 15) {
      // Reset beauty marks
      form.beautyMarks = null;
    }
    if (fromStep <= 16) {
      // Reset piercings
      form.piercings = null;
    }
    if (fromStep <= 17) {
      // Reset tattoos
      form.tattoos = null;
    }
    if (fromStep <= 18) {
      // Reset identity
      form.name = '';
      form.outfit = null;
      form.archetype = null;
      form.personalityTraits = [];
      form.bio = '';
    }
    if (fromStep <= 19) {
      // Reset base image selection
      state.baseImages = [];
      state.selectedBaseImageId = null;
      state.baseImageFineTunePrompt = '';
    }
    // Note: NSFW toggle is in finalize step, so it's not reset when going back
    // Profile pictures are generated after creation on the profile page.
  }
}

/** Default form values */
const DEFAULT_FORM: CharacterFormData = {
  // Step 0
  creationMethod: null,
  promptInput: undefined,
  promptEnhance: true, // Default to enabled (like studio)
  voiceMemoUrl: undefined,
  // Legacy fields
  customAppearancePrompt: undefined,
  customIdentityPrompt: undefined,
  customImagePrompt: undefined,
  // Step 1
  gender: 'female', // Preselected
  style: 'realistic', // Preselected
  // Step 2: General (Basic Appearance)
  ethnicity: null,
  ageRange: null,
  age: 25, // Keep for backward compatibility
  skinColor: null,
  // Step 3: Face (Facial Features)
  eyeColor: null,
  faceShape: null,
  // Step 3.5: Hair
  hairStyle: null,
  hairColor: null,
  // Step 4: Body
  bodyType: null,
  assSize: null,
  breastSize: null,
  breastType: null,
  // Step 6: Skin Features
  freckles: null,
  scars: null,
  beautyMarks: null,
  // Step 7: Body Modifications
  piercings: null,
  tattoos: null,
  // Step 9: Advanced
  voice: null,
  videoContentOptions: [],
  // Step 5
  name: '',
  outfit: null,
  archetype: null,
  personalityTraits: [],
  bio: '',
  // Generation
  nsfwEnabled: false,
  aspectRatio: '9:16',
  // qualityMode removed - see EP-045
  // LoRA training (default: enabled for better consistency)
  loraTrainingEnabled: true,
  // Profile picture set (null = skip by default)
  selectedProfilePictureSetId: null,
  // Existing Person Request Flow
  influencerRequestConsent: undefined,
  influencerRequestInstagram: undefined,
  influencerRequestTikTok: undefined,
  influencerRequestDescription: undefined,
};

/** Create the store with persistence */
export const useCharacterWizardStore = create<CharacterWizardState>()(
  persist(
    immer((set, get) => ({
      // Initial state
      step: 0, // Start at step 0 (creation method selection)
      steps: [], // Will be set when creation method is selected (or restored on rehydration)
      status: 'idle',
      form: { ...DEFAULT_FORM },
      characterId: null,
      baseImages: [],
      selectedBaseImageId: null,
      baseImageFineTunePrompt: '',
      // Base image generation tracking (for prompt-based flow)
      baseImageJobId: null,
      baseImageAllJobIds: null,
      baseImageGenerationStartedAt: null,
      profilePictureSet: {
        jobId: null,
        images: [],
        generating: false,
      },

      // Navigation actions
      setStep: (step) =>
        set((state) => {
          // If going to an earlier step, reset all steps from that step onwards
          if (step < state.step) {
            resetStepsFrom(state, step);
          }
          state.step = step;
        }),

      nextStep: () =>
        set((state) => {
          if (state.step < state.steps.length) {
            let nextStepNum = state.step + 1;
            const { form } = state;

            // Skip conditional steps for males (breast size/type)
            if (form.gender === 'male') {
              while (nextStepNum === 11 || nextStepNum === 12) {
                nextStepNum += 1;
              }
            }

            if (nextStepNum <= state.steps.length) {
              state.step = nextStepNum;
            }
          }
        }),

      prevStep: () =>
        set((state) => {
          if (state.step > 0) {
            let targetStep = state.step - 1;
            const { form } = state;

            // Skip conditional steps for males (breast size/type) when going backwards
            if (form.gender === 'male') {
              while (targetStep === 11 || targetStep === 12) {
                targetStep -= 1;
              }
            }

            if (targetStep >= 1) {
              // Reset all steps from targetStep onwards (including targetStep)
              resetStepsFrom(state, targetStep);
              state.step = targetStep;
            }
          }
        }),

      setStatus: (status) =>
        set((state) => {
          state.status = status;
        }),

      setCharacterId: (id) =>
        set((state) => {
          state.characterId = id;
        }),

      updateSteps: (
        method: 'presets' | 'prompt-based' | 'ai' | 'custom' | 'existing-person'
      ) =>
        set((state) => {
          if (method === 'prompt-based') {
            state.steps = PROMPT_BASED_STEPS;
          } else if (method === 'ai' || method === 'custom') {
            // AI and Custom flows use similar steps to prompt-based for now
            // Can be customized later
            state.steps = PROMPT_BASED_STEPS;
          } else if (method === 'existing-person') {
            state.steps = EXISTING_PERSON_STEPS;
          } else {
            // Default to presets
            state.steps = PRESETS_STEPS;
          }
          // Reset to step 1 of the selected flow
          state.step = 1;
        }),

      // Base image actions
      setBaseImages: (images) =>
        set((state) => {
          state.baseImages = images;
        }),

      selectBaseImage: (imageId) =>
        set((state) => {
          state.selectedBaseImageId = imageId;
        }),

      setBaseImageFineTunePrompt: (prompt) =>
        set((state) => {
          state.baseImageFineTunePrompt = prompt;
        }),

      replaceBaseImage: (imageId, newImage) =>
        set((state) => {
          const index = state.baseImages.findIndex((img) => img.id === imageId);
          if (index !== -1) {
            state.baseImages[index] = newImage;
          }
          // If this was the selected image, update selection
          if (state.selectedBaseImageId === imageId) {
            state.selectedBaseImageId = newImage.id;
          }
        }),

      setBaseImageJobIds: (jobId, allJobIds) =>
        set((state) => {
          state.baseImageJobId = jobId;
          state.baseImageAllJobIds = allJobIds;
          state.baseImageGenerationStartedAt = Date.now();
        }),

      clearBaseImageJobIds: () =>
        set((state) => {
          state.baseImageJobId = null;
          state.baseImageAllJobIds = null;
          state.baseImageGenerationStartedAt = null;
        }),

      // Profile picture set actions
      setProfilePictureSetGenerating: (generating) =>
        set((state) => {
          state.profilePictureSet.generating = generating;
        }),

      setProfilePictureSetJobId: (jobId) =>
        set((state) => {
          state.profilePictureSet.jobId = jobId;
        }),

      setProfilePictureSetImages: (images) =>
        set((state) => {
          state.profilePictureSet.images = images;
        }),

      addProfilePicture: (image) =>
        set((state) => {
          state.profilePictureSet.images.push(image);
        }),

      removeProfilePicture: (imageId) =>
        set((state) => {
          state.profilePictureSet.images =
            state.profilePictureSet.images.filter((img) => img.id !== imageId);
        }),

      updateProfilePicture: (imageId, updates) =>
        set((state) => {
          const index = state.profilePictureSet.images.findIndex(
            (img) => img.id === imageId
          );
          if (index !== -1) {
            Object.assign(state.profilePictureSet.images[index], updates);
          }
        }),

      // Form actions
      setField: (field, value) =>
        set((state) => {
          state.form[field] = value;

          // Auto-clear gender-specific fields when gender changes
          if (field === 'gender') {
            state.form.breastSize = null;
            state.form.breastType = null;
            state.form.bodyType = null;
            state.form.hairStyle = null;
          }
        }),

      setFormData: (data) =>
        set((state) => {
          Object.assign(state.form, data);
        }),

      resetForm: () =>
        set((state) => {
          state.step = 0;
          state.steps = [];
          state.status = 'idle';
          state.form = { ...DEFAULT_FORM };
          state.characterId = null;
          state.baseImages = [];
          state.selectedBaseImageId = null;
          state.baseImageFineTunePrompt = '';
          state.profilePictureSet = {
            jobId: null,
            images: [],
            generating: false,
          };
        }),

      // Validation
      isStepValid: (step) => {
        const { form, steps } = get();
        const currentStep = steps.find((s) => s.id === step);

        if (!currentStep) return false;

        // Step 0: Creation Method (if no method selected yet)
        if (step === 0 || !form.creationMethod) {
          return !!form.creationMethod;
        }

        // Validation based on creation method
        if (form.creationMethod === 'prompt-based') {
          switch (step) {
            case 1: // Prompt Input
              return !!form.promptInput?.trim();
            case 2: // Base Image Selection
              return !!get().selectedBaseImageId;
            case 3: // Finalize
              return true;
            default:
              return false;
          }
        } else if (
          form.creationMethod === 'ai' ||
          form.creationMethod === 'custom'
        ) {
          // AI and Custom flows use similar validation to prompt-based for now
          switch (step) {
            case 1: // AI Description or Custom Prompts
              return true; // Will be validated in their respective components
            case 2: // Base Image Selection
              return !!get().selectedBaseImageId;
            case 3: // Finalize
              return true;
            default:
              return false;
          }
        } else {
          // Presets flow - each step now validates only its own field
          switch (step) {
            case 1: // Style
              return !!form.gender && !!form.style;
            case 2: // Ethnicity
              return !!form.ethnicity;
            case 3: // Age Range
              return !!form.ageRange;
            case 4: // Skin Color
              return !!form.skinColor;
            case 5: // Eye Color
              return !!form.eyeColor;
            case 6: // Face Shape
              return !!form.faceShape;
            case 7: // Hair Style
              return !!form.hairStyle;
            case 8: // Hair Color
              return !!form.hairColor;
            case 9: // Body Type
              return !!form.bodyType;
            case 10: // Ass Size
              return !!form.assSize;
            case 11: // Breast Size (female only)
              return form.gender === 'male' || !!form.breastSize;
            case 12: // Breast Type (female only)
              return form.gender === 'male' || !!form.breastType;
            case 13: // Freckles
              return !!form.freckles;
            case 14: // Scars
              return !!form.scars;
            case 15: // Beauty Marks
              return !!form.beautyMarks;
            case 16: // Piercings
              return !!form.piercings;
            case 17: // Tattoos
              return !!form.tattoos;
            case 18: // Outfit
              return !!form.outfit;
            case 19: // Archetype
              return !!form.archetype;
            case 20: // Personality (name required, traits required, bio optional)
              return !!form.name?.trim() && form.personalityTraits.length > 0;
            case 21: // Base Image Selection
              return !!get().selectedBaseImageId;
            case 22: // Finalize
              return true;
            default:
              return false;
          }
        }
      },

      canProceed: () => {
        const { step, isStepValid } = get();
        return isStepValid(step);
      },

      getNextStepNumber: () => {
        const { step, steps, form } = get();
        if (step >= steps.length) return null;

        let nextStepNum = step + 1;

        // Skip conditional steps for males (breast size/type)
        if (form.gender === 'male') {
          while (nextStepNum === 11 || nextStepNum === 12) {
            nextStepNum += 1;
          }
        }

        return nextStepNum <= steps.length ? nextStepNum : null;
      },

      getPrevStepNumber: () => {
        const { step, form } = get();
        if (step <= 1) return null;

        let prevStepNum = step - 1;

        // Skip conditional steps for males (breast size/type) when going backwards
        if (form.gender === 'male') {
          while (prevStepNum === 11 || prevStepNum === 12) {
            prevStepNum -= 1;
          }
        }

        return prevStepNum >= 1 ? prevStepNum : null;
      },

      getEffectiveStepCount: () => {
        const { steps, form } = get();
        // For males, subtract 2 steps (breast size/type)
        if (form.gender === 'male') {
          return steps.length - 2;
        }
        return steps.length;
      },
    })),
    {
      name: 'ryla-character-wizard',
      storage: createJSONStorage(() => {
        // Wrap localStorage with error handling for quota exceeded
        const storage = localStorage;
        return {
          getItem: (name: string) => {
            try {
              return storage.getItem(name);
            } catch (error) {
              console.warn('Failed to read from localStorage:', error);
              return null;
            }
          },
          setItem: (name: string, value: string) => {
            try {
              storage.setItem(name, value);
            } catch (error) {
              // Handle quota exceeded error
              if (
                error instanceof DOMException &&
                error.name === 'QuotaExceededError'
              ) {
                console.error(
                  'localStorage quota exceeded. Clearing old wizard data...'
                );
                // Clear the wizard storage and try again
                try {
                  storage.removeItem('ryla-character-wizard');
                  storage.setItem(name, value);
                } catch (retryError) {
                  console.error(
                    'Failed to save after clearing storage:',
                    retryError
                  );
                  // If still failing, the data is too large - persist only essential data
                  throw new Error(
                    'Storage quota exceeded. Please complete the wizard in one session or clear browser storage.'
                  );
                }
              } else {
                throw error;
              }
            }
          },
          removeItem: (name: string) => {
            try {
              storage.removeItem(name);
            } catch (error) {
              console.warn('Failed to remove from localStorage:', error);
            }
          },
        };
      }),
      partialize: (state) => {
        // Only persist minimal image data to avoid quota issues
        // Store only IDs and essential metadata, not full image objects
        const minimalBaseImages = state.baseImages.map((img) => ({
          id: img.id,
          url: img.thumbnailUrl || img.url, // Prefer thumbnail if available
          s3Key: img.s3Key,
        }));

        const minimalProfilePictures = state.profilePictureSet.images.map(
          (img) => ({
            id: img.id,
            positionId: img.positionId,
            positionName: img.positionName,
            url: img.thumbnailUrl || img.url, // Prefer thumbnail if available
            s3Key: img.s3Key,
          })
        );

        return {
          step: state.step,
          status: state.status,
          form: state.form,
          characterId: state.characterId,
          baseImages: minimalBaseImages,
          selectedBaseImageId: state.selectedBaseImageId,
          baseImageFineTunePrompt: state.baseImageFineTunePrompt,
          // Persist job IDs for resume after refresh
          baseImageJobId: state.baseImageJobId,
          baseImageAllJobIds: state.baseImageAllJobIds,
          baseImageGenerationStartedAt: state.baseImageGenerationStartedAt,
          profilePictureSet: {
            ...state.profilePictureSet,
            images: minimalProfilePictures,
          },
        };
      },
      onRehydrateStorage: () => (state) => {
        // Restore steps array based on creationMethod when rehydrating from localStorage
        if (state && state.form.creationMethod && state.steps.length === 0) {
          if (state.form.creationMethod === 'prompt-based') {
            state.steps = PROMPT_BASED_STEPS;
          } else if (state.form.creationMethod === 'presets') {
            state.steps = PRESETS_STEPS;
          }
        }
      },
    }
  )
);

/** Helper: Get current step info */
export const useCurrentStep = () => {
  const step = useCharacterWizardStore((s) => s.step);
  const steps = useCharacterWizardStore((s) => s.steps);
  if (steps.length === 0) return null; // Return null if steps not initialized
  return steps.find((s) => s.id === step) || steps[0] || null;
};

/** Helper: Get progress percentage */
export const useWizardProgress = () => {
  const step = useCharacterWizardStore((s) => s.step);
  const getEffectiveStepCount = useCharacterWizardStore(
    (s) => s.getEffectiveStepCount
  );
  const steps = useCharacterWizardStore((s) => s.steps);
  if (steps.length === 0) return 0; // Return 0 if steps not initialized yet
  const effectiveCount = getEffectiveStepCount();
  return Math.round((step / effectiveCount) * 100);
};

/** Utility: Clear wizard storage (useful for debugging or quota issues) */
export const clearWizardStorage = () => {
  if (typeof window !== 'undefined') {
    try {
      localStorage.removeItem('ryla-character-wizard');
      console.log('Wizard storage cleared');
    } catch (error) {
      console.error('Failed to clear wizard storage:', error);
    }
  }
};

/**
 * Helper: Check if current step is valid and can proceed
 * This hook subscribes to form data changes so it re-renders when validation state changes
 */
export const useCanProceed = () => {
  const step = useCharacterWizardStore((s) => s.step);
  const form = useCharacterWizardStore((s) => s.form);
  const steps = useCharacterWizardStore((s) => s.steps);
  const selectedBaseImageId = useCharacterWizardStore(
    (s) => s.selectedBaseImageId
  );

  // Find current step definition
  const currentStep = steps.find((s) => s.id === step);

  // If no step definition, check step 0 (creation method selection)
  if (!currentStep) {
    return step === 0 ? !!form.creationMethod : false;
  }

  // Step 0: Creation Method (if no method selected yet)
  if (step === 0 || !form.creationMethod) {
    return !!form.creationMethod;
  }

  // Validation based on creation method
  if (form.creationMethod === 'prompt-based') {
    // 4-step flow: Prompt → Identity → Base Image → Finalize
    switch (step) {
      case 1: // Prompt Input
        return !!form.promptInput?.trim();
      case 2: // Identity (name required, others optional for prompt-based)
        return !!form.name?.trim();
      case 3: // Base Image Selection
        return !!selectedBaseImageId;
      case 4: // Finalize
        return true;
      default:
        return false;
    }
  } else if (form.creationMethod === 'ai' || form.creationMethod === 'custom') {
    // AI and Custom flows use similar validation to prompt-based
    switch (step) {
      case 1: // AI Description or Custom Prompts
        return true; // Will be validated in their respective components
      case 2: // Identity
        return !!form.name?.trim();
      case 3: // Base Image Selection
        return !!selectedBaseImageId;
      case 4: // Finalize
        return true;
      default:
        return false;
    }
  } else {
    // Presets flow - 20-step flow, each step validates only its own field
    switch (step) {
      case 1: // Style
        return !!form.gender && !!form.style;
      case 2: // Ethnicity
        return !!form.ethnicity;
      case 3: // Age Range
        return !!form.ageRange;
      case 4: // Skin Color
        return !!form.skinColor;
      case 5: // Eye Color
        return !!form.eyeColor;
      case 6: // Face Shape
        return !!form.faceShape;
      case 7: // Hair Style
        return !!form.hairStyle;
      case 8: // Hair Color
        return !!form.hairColor;
      case 9: // Body Type
        return !!form.bodyType;
      case 10: // Ass Size
        return !!form.assSize;
      case 11: // Breast Size (female only)
        return form.gender === 'male' || !!form.breastSize;
      case 12: // Breast Type (female only)
        return form.gender === 'male' || !!form.breastType;
      case 13: // Freckles
        return !!form.freckles;
      case 14: // Scars
        return !!form.scars;
      case 15: // Beauty Marks
        return !!form.beautyMarks;
      case 16: // Piercings
        return !!form.piercings;
      case 17: // Tattoos
        return !!form.tattoos;
      case 18: // Outfit
        return !!form.outfit;
      case 19: // Archetype
        return !!form.archetype;
      case 20: // Personality (name required, traits required, bio optional)
        return !!form.name?.trim() && form.personalityTraits.length > 0;
      case 21: // Base Image Selection
        return !!selectedBaseImageId;
      case 22: // Finalize
        return true;
      default:
        return false;
    }
  }
};
