/* AUTO-GENERATED — DO NOT EDIT */
export type SpriteItem = { id: string; title: string; group?: string; w: number; h: number; x: number; y: number; };

export const SPRITE_URL = "/images/company-logos/sprite.webp?v=2025-10-06";
export const SPRITE_W = 6369;
export const SPRITE_H = 6315;

export const SPRITE_ITEMS: SpriteItem[] = [
    {
        id: "avatars-avatar_1",
        group: "avatars",
        title: "Avatar 1",
        w: 382,
        h: 382,
        x: 0,
        y: 5933,
    },
    {
        id: "avatars-avatar_2",
        group: "avatars",
        title: "Avatar 2",
        w: 230,
        h: 336,
        x: 6009,
        y: 1736,
    },
    {
        id: "avatars-avatar_3",
        group: "avatars",
        title: "Avatar 3",
        w: 510,
        h: 510,
        x: 559,
        y: 4975,
    },
    {
        id: "avatars-avatar_4",
        group: "avatars",
        title: "Avatar 4",
        w: 200,
        h: 200,
        x: 6009,
        y: 3737,
    },
    {
        id: "avatars-avatar_5",
        group: "avatars",
        title: "Avatar 5",
        w: 150,
        h: 150,
        x: 6215,
        y: 3532,
    },
    {
        id: "avatars-avatar_7",
        group: "avatars",
        title: "Avatar 7",
        w: 230,
        h: 336,
        x: 6009,
        y: 2076,
    },
    {
        id: "avatars-avatar_8",
        group: "avatars",
        title: "Avatar 8",
        w: 230,
        h: 296,
        x: 6009,
        y: 3056,
    },
    {
        id: "avatars-avatar_9",
        group: "avatars",
        title: "Avatar 9",
        w: 230,
        h: 336,
        x: 6009,
        y: 2416,
    },
    {
        id: "avatars-avatar_10",
        group: "avatars",
        title: "Avatar 10",
        w: 249,
        h: 364,
        x: 6009,
        y: 819,
    },
    {
        id: "award-ranking",
        group: "",
        title: "Award Ranking",
        w: 126,
        h: 42,
        x: 6243,
        y: 2009,
    },
    {
        id: "backgrounds-Ellipse",
        group: "backgrounds",
        title: "Ellipse",
        w: 286,
        h: 285,
        x: 6009,
        y: 1187,
    },
    {
        id: "backgrounds-Ellipse2",
        group: "backgrounds",
        title: "Ellipse2",
        w: 202,
        h: 201,
        x: 6009,
        y: 3532,
    },
    {
        id: "backgrounds-girl",
        group: "backgrounds",
        title: "Girl",
        w: 391,
        h: 511,
        x: 5548,
        y: 1673,
    },
    {
        id: "backgrounds-happy_users_bg",
        group: "backgrounds",
        title: "Happy Users Bg",
        w: 307,
        h: 256,
        x: 6009,
        y: 1476,
    },
    {
        id: "blurred-characters-black-black",
        group: "blurred-characters",
        title: "Black Black",
        w: 499,
        h: 729,
        x: 1780,
        y: 991,
    },
    {
        id: "blurred-characters-black-blonde",
        group: "blurred-characters",
        title: "Black Blonde",
        w: 499,
        h: 729,
        x: 2644,
        y: 1848,
    },
    {
        id: "blurred-characters-black-brunette",
        group: "blurred-characters",
        title: "Black Brunette",
        w: 499,
        h: 729,
        x: 0,
        y: 4242,
    },
    {
        id: "blurred-characters-black-ginger",
        group: "blurred-characters",
        title: "Black Ginger",
        w: 499,
        h: 729,
        x: 503,
        y: 4242,
    },
    {
        id: "blurred-characters-white-black",
        group: "blurred-characters",
        title: "White Black",
        w: 499,
        h: 729,
        x: 1006,
        y: 4242,
    },
    {
        id: "blurred-characters-white-blonde",
        group: "blurred-characters",
        title: "White Blonde",
        w: 499,
        h: 729,
        x: 1509,
        y: 4242,
    },
    {
        id: "blurred-characters-white-brunette",
        group: "blurred-characters",
        title: "White Brunette",
        w: 499,
        h: 729,
        x: 2012,
        y: 4242,
    },
    {
        id: "blurred-characters-white-ginger",
        group: "blurred-characters",
        title: "White Ginger",
        w: 499,
        h: 729,
        x: 2515,
        y: 4242,
    },
    {
        id: "body-types-chubby-body-type",
        group: "body-types",
        title: "Chubby Body Type",
        w: 855,
        h: 710,
        x: 1800,
        y: 2712,
    },
    {
        id: "body-types-muscular-body-type",
        group: "body-types",
        title: "Muscular Body Type",
        w: 896,
        h: 713,
        x: 900,
        y: 2712,
    },
    {
        id: "body-types-petite-body-type",
        group: "body-types",
        title: "Petite Body Type",
        w: 896,
        h: 816,
        x: 880,
        y: 991,
    },
    {
        id: "body-types-pregnant-body-type",
        group: "body-types",
        title: "Pregnant Body Type",
        w: 896,
        h: 801,
        x: 844,
        y: 1848,
    },
    {
        id: "body-types-slim-body-type",
        group: "body-types",
        title: "Slim Body Type",
        w: 896,
        h: 732,
        x: 0,
        y: 2712,
    },
    {
        id: "body-types-thick-body-type",
        group: "body-types",
        title: "Thick Body Type",
        w: 896,
        h: 792,
        x: 1744,
        y: 1848,
    },
    {
        id: "brands-aixploria-logo",
        group: "brands",
        title: "Aixploria Logo",
        w: 400,
        h: 90,
        x: 3018,
        y: 4733,
    },
    {
        id: "brands-citypaper-logo",
        group: "brands",
        title: "Citypaper Logo",
        w: 400,
        h: 117,
        x: 5548,
        y: 5265,
    },
    {
        id: "brands-entrepreneur-logo",
        group: "brands",
        title: "Entrepreneur Logo",
        w: 92,
        h: 18,
        x: 6262,
        y: 1061,
    },
    {
        id: "brands-nsfwaii-logo",
        group: "brands",
        title: "Nsfwaii Logo",
        w: 85,
        h: 38,
        x: 6262,
        y: 891,
    },
    {
        id: "brands-taaft-logo",
        group: "brands",
        title: "Taaft Logo",
        w: 79,
        h: 32,
        x: 6262,
        y: 1025,
    },
    {
        id: "brands-the-ai-journal",
        group: "brands",
        title: "The Ai Journal",
        w: 439,
        h: 84,
        x: 2659,
        y: 3302,
    },
    {
        id: "brands-toolify-ai-logo",
        group: "brands",
        title: "Toolify Ai Logo",
        w: 455,
        h: 100,
        x: 5548,
        y: 5386,
    },
    {
        id: "brands-top-ai-tools-logo",
        group: "brands",
        title: "Top Ai Tools Logo",
        w: 96,
        h: 32,
        x: 6262,
        y: 933,
    },
    {
        id: "brands-zerohedge-logo",
        group: "brands",
        title: "Zerohedge Logo",
        w: 584,
        h: 132,
        x: 4776,
        y: 4054,
    },
    {
        id: "breast-sizes-big-breast-size",
        group: "breast-sizes",
        title: "Big Breast Size",
        w: 489,
        h: 383,
        x: 486,
        y: 5494,
    },
    {
        id: "breast-sizes-flat-breast-size",
        group: "breast-sizes",
        title: "Flat Breast Size",
        w: 636,
        h: 487,
        x: 3018,
        y: 4242,
    },
    {
        id: "breast-sizes-huge-breast-size",
        group: "breast-sizes",
        title: "Huge Breast Size",
        w: 589,
        h: 441,
        x: 4289,
        y: 4242,
    },
    {
        id: "breast-sizes-regular-breast-size",
        group: "breast-sizes",
        title: "Regular Breast Size",
        w: 429,
        h: 352,
        x: 979,
        y: 5494,
    },
    {
        id: "breast-sizes-small-breast-size",
        group: "breast-sizes",
        title: "Small Breast Size",
        w: 661,
        h: 585,
        x: 4776,
        y: 3465,
    },
    {
        id: "breast-types-fake-breast-type",
        group: "breast-types",
        title: "Fake Breast Type",
        w: 647,
        h: 537,
        x: 3303,
        y: 2712,
    },
    {
        id: "breast-types-perky-breast-type",
        group: "breast-types",
        title: "Perky Breast Type",
        w: 627,
        h: 455,
        x: 3658,
        y: 4242,
    },
    {
        id: "breast-types-regular-breast-type",
        group: "breast-types",
        title: "Regular Breast Type",
        w: 482,
        h: 435,
        x: 0,
        y: 5494,
    },
    {
        id: "breast-types-saggy-breast-type",
        group: "breast-types",
        title: "Saggy Breast Type",
        w: 555,
        h: 515,
        x: 0,
        y: 4975,
    },
    {
        id: "breast-types-torpedo-breast-type",
        group: "breast-types",
        title: "Torpedo Breast Type",
        w: 640,
        h: 586,
        x: 2659,
        y: 2712,
    },
    {
        id: "cards-logos-mastercard",
        group: "cards-logos",
        title: "Mastercard",
        w: 28,
        h: 19,
        x: 6338,
        y: 530,
    },
    {
        id: "cards-logos-visa",
        group: "cards-logos",
        title: "Visa",
        w: 28,
        h: 19,
        x: 6338,
        y: 553,
    },
    {
        id: "character-age-compressed_adult-character",
        group: "character-age",
        title: "Compressed Adult Character",
        w: 840,
        h: 889,
        x: 2316,
        y: 0,
    },
    {
        id: "character-age-compressed_young-character",
        group: "character-age",
        title: "Compressed Young Character",
        w: 840,
        h: 871,
        x: 2316,
        y: 893,
    },
    {
        id: "character-age-compressed_youth-character",
        group: "character-age",
        title: "Compressed Youth Character",
        w: 840,
        h: 815,
        x: 3160,
        y: 0,
    },
    {
        id: "character-age-mature-character",
        group: "character-age",
        title: "Mature Character",
        w: 840,
        h: 860,
        x: 0,
        y: 1848,
    },
    {
        id: "character-relationships-babysitter-relationship",
        group: "character-relationships",
        title: "Babysitter Relationship",
        w: 768,
        h: 822,
        x: 3160,
        y: 1747,
    },
    {
        id: "character-relationships-college-roommate-relationship",
        group: "character-relationships",
        title: "College Roommate Relationship",
        w: 768,
        h: 790,
        x: 0,
        y: 3448,
    },
    {
        id: "character-relationships-crush-relationship",
        group: "character-relationships",
        title: "Crush Relationship",
        w: 768,
        h: 792,
        x: 4004,
        y: 2427,
    },
    {
        id: "character-relationships-ex-relationship",
        group: "character-relationships",
        title: "Ex Relationship",
        w: 768,
        h: 790,
        x: 772,
        y: 3448,
    },
    {
        id: "character-relationships-first-date-relationship",
        group: "character-relationships",
        title: "First Date Relationship",
        w: 768,
        h: 810,
        x: 4004,
        y: 0,
    },
    {
        id: "character-relationships-neighbor-relationship",
        group: "character-relationships",
        title: "Neighbor Relationship",
        w: 768,
        h: 774,
        x: 3860,
        y: 3448,
    },
    {
        id: "character-relationships-step-mom-relationship",
        group: "character-relationships",
        title: "Step Mom Relationship",
        w: 768,
        h: 790,
        x: 1544,
        y: 3448,
    },
    {
        id: "character-relationships-step-sister-relationship",
        group: "character-relationships",
        title: "Step Sister Relationship",
        w: 768,
        h: 788,
        x: 2316,
        y: 3448,
    },
    {
        id: "character-relationships-wife-relationship",
        group: "character-relationships",
        title: "Wife Relationship",
        w: 768,
        h: 810,
        x: 4004,
        y: 814,
    },
    {
        id: "character-relationships-your-boss-relationship",
        group: "character-relationships",
        title: "Your Boss Relationship",
        w: 768,
        h: 777,
        x: 3088,
        y: 3448,
    },
    {
        id: "character-relationships-your-girlfriend-relationship",
        group: "character-relationships",
        title: "Your Girlfriend Relationship",
        w: 768,
        h: 795,
        x: 4004,
        y: 1628,
    },
    {
        id: "character-relationships-your-teacher-relationship",
        group: "character-relationships",
        title: "Your Teacher Relationship",
        w: 768,
        h: 774,
        x: 4776,
        y: 0,
    },
    {
        id: "character-styles-anime-character-style",
        group: "character-styles",
        title: "Anime Character Style",
        w: 472,
        h: 987,
        x: 4776,
        y: 778,
    },
    {
        id: "character-styles-realistic-character-style",
        group: "character-styles",
        title: "Realistic Character Style",
        w: 457,
        h: 990,
        x: 4776,
        y: 2471,
    },
    {
        id: "character-types-athlete-type",
        group: "character-types",
        title: "Athlete Type",
        w: 768,
        h: 987,
        x: 0,
        y: 0,
    },
    {
        id: "character-types-lady-boss-type",
        group: "character-types",
        title: "Lady Boss Type",
        w: 768,
        h: 987,
        x: 772,
        y: 0,
    },
    {
        id: "character-types-manic-pixie-girl-type",
        group: "character-types",
        title: "Manic Pixie Girl Type",
        w: 768,
        h: 987,
        x: 1544,
        y: 0,
    },
    {
        id: "countries-britain",
        group: "countries",
        title: "Britain",
        w: 52,
        h: 52,
        x: 6262,
        y: 969,
    },
    {
        id: "countries-china",
        group: "countries",
        title: "China",
        w: 42,
        h: 42,
        x: 6318,
        y: 969,
    },
    {
        id: "countries-france",
        group: "countries",
        title: "France",
        w: 35,
        h: 35,
        x: 6334,
        y: 819,
    },
    {
        id: "countries-germany",
        group: "countries",
        title: "Germany",
        w: 34,
        h: 34,
        x: 6262,
        y: 1083,
    },
    {
        id: "countries-india",
        group: "countries",
        title: "India",
        w: 34,
        h: 34,
        x: 6300,
        y: 1083,
    },
    {
        id: "countries-liberia",
        group: "countries",
        title: "Liberia",
        w: 24,
        h: 24,
        x: 6338,
        y: 502,
    },
    {
        id: "crown",
        group: "",
        title: "Crown",
        w: 1,
        h: 1,
        x: 6366,
        y: 502,
    },
    {
        id: "cursor",
        group: "",
        title: "Cursor",
        w: 258,
        h: 296,
        x: 6009,
        y: 2756,
    },
    {
        id: "eyes-colors-blue-eyes-color",
        group: "eyes-colors",
        title: "Blue Eyes Color",
        w: 398,
        h: 100,
        x: 3573,
        y: 2573,
    },
    {
        id: "eyes-colors-brown-eyes-color",
        group: "eyes-colors",
        title: "Brown Eyes Color",
        w: 430,
        h: 100,
        x: 4004,
        y: 3327,
    },
    {
        id: "eyes-colors-green-eyes-color",
        group: "eyes-colors",
        title: "Green Eyes Color",
        w: 409,
        h: 100,
        x: 3160,
        y: 2573,
    },
    {
        id: "eyes-colors-grey-eyes-color",
        group: "eyes-colors",
        title: "Grey Eyes Color",
        w: 434,
        h: 100,
        x: 4004,
        y: 3223,
    },
    {
        id: "fireworks",
        group: "",
        title: "Fireworks",
        w: 614,
        h: 408,
        x: 4882,
        y: 4242,
    },
    {
        id: "haircut-colors-black-haircut",
        group: "haircut-colors",
        title: "Black Haircut",
        w: 163,
        h: 163,
        x: 6183,
        y: 3941,
    },
    {
        id: "haircut-colors-blonde-haircut",
        group: "haircut-colors",
        title: "Blonde Haircut",
        w: 160,
        h: 160,
        x: 6009,
        y: 4115,
    },
    {
        id: "haircut-colors-brunette-haircut",
        group: "haircut-colors",
        title: "Brunette Haircut",
        w: 145,
        h: 145,
        x: 6213,
        y: 3737,
    },
    {
        id: "haircut-colors-ginger-haircut",
        group: "haircut-colors",
        title: "Ginger Haircut",
        w: 170,
        h: 170,
        x: 6009,
        y: 3941,
    },
    {
        id: "haircut-styles-braids-haircut",
        group: "haircut-styles",
        title: "Braids Haircut",
        w: 422,
        h: 429,
        x: 5548,
        y: 3547,
    },
    {
        id: "haircut-styles-bun-haircut",
        group: "haircut-styles",
        title: "Bun Haircut",
        w: 420,
        h: 429,
        x: 5548,
        y: 3980,
    },
    {
        id: "haircut-styles-curly-long-haircut",
        group: "haircut-styles",
        title: "Curly Long Haircut",
        w: 424,
        h: 428,
        x: 5548,
        y: 3115,
    },
    {
        id: "haircut-styles-hair-bow-haircut",
        group: "haircut-styles",
        title: "Hair Bow Haircut",
        w: 420,
        h: 436,
        x: 5548,
        y: 2675,
    },
    {
        id: "haircut-styles-long-haircut",
        group: "haircut-styles",
        title: "Long Haircut",
        w: 418,
        h: 419,
        x: 5548,
        y: 4842,
    },
    {
        id: "haircut-styles-short-haircut",
        group: "haircut-styles",
        title: "Short Haircut",
        w: 419,
        h: 425,
        x: 5548,
        y: 4413,
    },
    {
        id: "how-it-work-chat",
        group: "how-it-work",
        title: "Chat",
        w: 720,
        h: 312,
        x: 1073,
        y: 4975,
    },
    {
        id: "how-it-work-photo",
        group: "how-it-work",
        title: "Photo",
        w: 335,
        h: 172,
        x: 6009,
        y: 3356,
    },
    {
        id: "logo-product",
        group: "",
        title: "Logo Product",
        w: 114,
        h: 45,
        x: 6243,
        y: 2195,
    },
    {
        id: "logo-xl",
        group: "",
        title: "Logo Xl",
        w: 112,
        h: 150,
        x: 6243,
        y: 1736,
    },
    {
        id: "logo",
        group: "",
        title: "Logo",
        w: 29,
        h: 41,
        x: 6338,
        y: 457,
    },
    {
        id: "placeholders-featured-by-users-card",
        group: "placeholders",
        title: "Featured By Users Card",
        w: 360,
        h: 453,
        x: 6009,
        y: 0,
    },
    {
        id: "play-button",
        group: "",
        title: "Play Button",
        w: 68,
        h: 68,
        x: 6262,
        y: 819,
    },
    {
        id: "turn-types-dirty-talk-type",
        group: "turn-types",
        title: "Dirty Talk Type",
        w: 325,
        h: 358,
        x: 6009,
        y: 457,
    },
    {
        id: "turn-types-dominance-type",
        group: "turn-types",
        title: "Dominance Type",
        w: 457,
        h: 561,
        x: 5548,
        y: 0,
    },
    {
        id: "turn-types-high-heels-type",
        group: "turn-types",
        title: "High Heels Type",
        w: 415,
        h: 512,
        x: 5548,
        y: 1157,
    },
    {
        id: "turn-types-latex-or-leather-type",
        group: "turn-types",
        title: "Latex Or Leather Type",
        w: 723,
        h: 924,
        x: 3160,
        y: 819,
    },
    {
        id: "turn-types-stockings-and-lingerie-type",
        group: "turn-types",
        title: "Stockings And Lingerie Type",
        w: 368,
        h: 588,
        x: 5548,
        y: 565,
    },
    {
        id: "want-to-try-blindfold-try",
        group: "want-to-try",
        title: "Blindfold Try",
        w: 110,
        h: 115,
        x: 6243,
        y: 1890,
    },
    {
        id: "want-to-try-bondage-try",
        group: "want-to-try",
        title: "Bondage Try",
        w: 406,
        h: 483,
        x: 5548,
        y: 2188,
    },
    {
        id: "want-to-try-foot-try",
        group: "want-to-try",
        title: "Foot Try",
        w: 650,
        h: 698,
        x: 4776,
        y: 1769,
    },
    {
        id: "want-to-try-humiliation-try",
        group: "want-to-try",
        title: "Humiliation Try",
        w: 876,
        h: 853,
        x: 0,
        y: 991,
    },
    {
        id: "want-to-try-public-play-try",
        group: "want-to-try",
        title: "Public Play Try",
        w: 110,
        h: 115,
        x: 6243,
        y: 2076,
    },
];
